/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Parser;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TRUE = 5;
  /** RegularExpression Id. */
  int FALSE = 6;
  /** RegularExpression Id. */
  int NEW = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int THEN = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int WHILE = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int Id = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int MINUS = 16;
  /** RegularExpression Id. */
  int TIMES = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int LPAR = 19;
  /** RegularExpression Id. */
  int RPAR = 20;
  /** RegularExpression Id. */
  int DEF = 21;
  /** RegularExpression Id. */
  int LBRA = 22;
  /** RegularExpression Id. */
  int RBRA = 23;
  /** RegularExpression Id. */
  int EQ = 24;
  /** RegularExpression Id. */
  int SCN = 25;
  /** RegularExpression Id. */
  int CM = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int GREATER = 29;
  /** RegularExpression Id. */
  int LOWER = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int LEQUAL = 32;
  /** RegularExpression Id. */
  int GEQUAL = 33;
  /** RegularExpression Id. */
  int EQUALS = 34;
  /** RegularExpression Id. */
  int DIFF = 35;
  /** RegularExpression Id. */
  int AFFECTATION = 36;
  /** RegularExpression Id. */
  int DEREF = 37;
  /** RegularExpression Id. */
  int DOUBLESCN = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
      "<EOF>",
      "\" \"",
      "\"\\t\"",
      "\"\\r\"",
      "\"\\n\"",
      "\"true\"",
      "\"false\"",
      "\"new\"",
      "\"if\"",
      "\"then\"",
      "\"else\"",
      "\"while\"",
      "\"print\"",
      "<Id>",
      "<NUM>",
      "\"+\"",
      "\"-\"",
      "\"*\"",
      "\"/\"",
      "\"(\"",
      "\")\"",
      "\"def \"",
      "\"{\"",
      "\"}\"",
      "\"=\"",
      "\";\"",
      "\",\"",
      "\"&&\"",
      "\"||\"",
      "\">\"",
      "\"<\"",
      "\"~\"",
      "\"<=\"",
      "\">=\"",
      "\"==\"",
      "\"~=\"",
      "\":=\"",
      "\"!\"",
      "\";;\"",
  };

}
